stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add lftp
  script:
    - lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "mirror -R ./ /path/to/your/public_html/ ; quit"
  only:
    - main
