image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y lftp
    - lftp -e "set ssl:verify-certificate no; set ftp:ssl-allow no; mirror -R build /public_html/; quit" -u "omkarkhaire@omkarkhaire.in","#Q%0Nl%[xrB3" ftp.omkarkhaire.in
  only:
    - main
